### ISSUE TITLE
multiple tags

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/tagrs#9]
I have a few tests:

```rust
    #[tag("fast")]
    #[test]
    fn outputs_help() -> Result<()> {
        // some assertions
        Ok(())
    }

    #[tag("slow")]
    #[test]
    fn outputs_something_else() -> Result<()> {
        // some assertions
        Ok(())
    }
```

when I run this:

```bash
TTAG=slow,fast cargo test
```

It won't any both tests, both `outputs_help` and `outputs_something_else` will be ignored. Let's allow multiple tags to be provided

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#11](https://github.com/h1alexbel/tagrs/issues/11) is still not solved.
